### PR TITLE
Optimize GameServer /announce and add website announcements

### PR DESCRIPTION
**Pull request by sudokoko**
This PR changes a few things pertaining to announcements.

* Implements a web-based announcements system
* Optimizes /announce to use a StringBuilder

First off, I improved the /announce game server endpoint in 144e952bde2bf80d0e8fb52212ec4c288091fa8b to use a string builder instead of re-assigning string modifications over and over again.

Second, I implemented a website-based announcements system in 4f89c10f1ccceb325a7dcc978c6ac41385ed3f37 which will allow instance administrators to send out announcements to users. I opted to condense the changes across several commits into one singular commit to improve organization.

Last, I added Discord webhook support in d5b773926eb9ff645bc39ca749e74dfb8d8c0bba which sends new announcements to the configured Discord webhook, if set up.

fdd6e2db2f224469d39e9d954e0e01af8c8626ae simply fixes a web display issue.

<details>
<summary>Images</summary>
Screenshot 2023-06-20 at 9 04 14 PM
Screenshot 2023-06-20 at 9 04 55 PM
</details>

### CODE REVIEW

**Comment by m88youngling** [comment]
Finally, we'll be able to send maintenance notices to users before I break production!

**Review by daggintosh — APPROVED** [review]
.

**Review by Zaprit — APPROVED** [review]
Looks good to me

**Comment by W0lf4llo** [comment]
LGTM

**Comment by SammyGoesHowdy** [comment]
seems like code, so i'd approve

iQoOCIkA_400x400

**Review by Slendy — APPROVED** [review]
lgtm

**Pull request merged**
