### PR TITLE
useless, as those get caught by default

### PR DESCRIPTION
**Pull request by McMistrzYT**
removed some cases in the user controller as they change absolutely nothing and get caught by default anyway

### CODE REVIEW

**Comment by sudokoko** [comment]
Wasn't this occurrence previously discussed? Feel free to correct me if I'm wrong but I believe Slendy explained why they're there.

**Comment by McMistrzYT** [comment]
they do absolutely nothing because default is right under them no?

**Comment by sudokoko** [comment]
Let me quickly find his explanation, moment.

**Comment by sudokoko** [comment]
This was similar to or the same reason #614 was closed.

> Rider complains if you don't handle all possible enum values in a switch statement. Having all possible cases also has the benefit of being more verbose and self-documenting.

**Comment by McMistrzYT** [comment]
makes sense i guess

**Pull request closed without merging**
