### PR TITLE
Added some more GameIDs

### PR DESCRIPTION
**Pull request by FridiNaTor1**
Added a Hub ID and 4 Move IDs (Sackboy’s Prehistoric Moves). And removed a duplicated GameID

### CODE REVIEW

**Comment by TorutheRedFox** [comment]
quick note, you removed BCET70011, and forgot about NPEA00449 and BCET70055 for Hub

**Comment by FridiNaTor1** [comment]
> quick note, you removed BCET70011, and forgot about NPEA00449 and BCET70055 for Hub

I removed a duplicate of BCET70011 if you look at the entire file you can see BCET70011 is right under the `//Debug, Beta and Demo` section for LBP1.
Not sure what you mean by I forgot about NPEA00449 and BCET70055? They are there, here's the full line:

-         //HUB
        "BCET70055",
        "NPEA00449",
        "NPHA80261",
        "NPUA80967",

Am I missing something here?

**Comment by TorutheRedFox** [comment]
> > quick note, you removed BCET70011, and forgot about NPEA00449 and BCET70055 for Hub
> 
> I removed a duplicate of BCET70011 if you look at the entire file you can see BCET70011 is right under the `//Debug, Beta and Demo` section for LBP1. Not sure what you mean by I forgot about NPEA00449 and BCET70055? They are there, here's the full line:
> 
> * ```
>       //HUB
>     "BCET70055",
>     "NPEA00449",
>     "NPHA80261",
>     "NPUA80967",
>   ```
> 
> Am I missing something here?

must've missed it then, or github's diff viewer was acting up lol

**Comment by Arcadius2006** [comment]
SBPM doesn't go online though

**Review by Slendy — APPROVED** [review]
LGTM

**Pull request merged**
