### PR TITLE
Implement checkboxes in slot settings to toggle various slot properties

### PR DESCRIPTION
**Pull request by FeTetra**
This PR will allow users to modify slot properties: Locked, Shareable, SubLevel, or LBP1Only. This is done via checkboxes located in the slotsettings page.

<sup><sub>finally lol</sub></sup>

### CODE REVIEW

**Comment by PorkchopGMX** [comment]
third time's the charm!

**Comment by FeTetra** [comment]
> third time's the charm!

shhh

**Comment by FeTetra** [comment]
forgor to update the branch

**Comment by FeTetra** [comment]
im an idiot

**Comment by FeTetra** [comment]
Not sure if giving the divs both the `button` and `label` classes is extremely cursed or not. Also this can be done without inline JS. I chose not to so the code could remain consistent. I can switch to using razor for enabling/disabling the `selected` class.

**Review by Slendy — CHANGES_REQUESTED** [review]
A few more styling changes, initial state handling, and better checkbox handling code

**Comment by FeTetra** [comment]
Cool thanks, I read through these and they seemed commit-able.

**Review by Slendy — APPROVED** [review]

**Review by sudokoko — APPROVED** [review]

**Pull request merged**
