### PR TITLE
Containerize Project Lighthouse

### PR DESCRIPTION
**Pull request by Slendy**
Adds a proper Dockerfile and updates docker-compose to have services for gameserver, API, and website along with services for redis and mariadb. This is helpful for spinning up Project Lighthouse instances.

### CODE REVIEW

**Comment by daggintosh** [comment]
should wait on this until #581 probably

**Comment by W0lf4llo** [comment]
Update the branch pls 😎

**Comment by daggintosh** [comment]
> Update the branch pls 😎

It's been updated twice now, happy? Or do we need to call the Slendy?

And he'll probably kill us because he's immensely powerful and I have no plan.

**Comment by Slendy** [comment]
LGTM
image

**Pull request merged**
