### PR TITLE
Implement basic filters and LBP2 CrossController fixes

### PR DESCRIPTION
**Pull request by jackcaver**
implemeted label filters for lbp2 and lbp vita

### CODE REVIEW

**Review by sudokoko — CHANGES_REQUESTED** [review]
Hey! This looks good, however in testing we noticed that cross controller levels appear in LBP3 though it's not possible to play them. Otherwise, everything appears okay. I'll wait for this to be fixed to nudge Slendy to do the final review.

**Review by sudokoko — APPROVED** [review]
LGTM

**Comment by jackcaver** [comment]
wait, before merging i need to do 1 more thing as i have found 1 bug in lbp3

**Comment by jackcaver** [comment]
ok, now everything should be fine

**Pull request merged**
