### PR TITLE
Implement story mode player counts endpoint

### PR DESCRIPTION
**Pull request by Slendy**
I found some packet captures for /slots/developer, idk how the game actually uses this but I thought I may as well implement it.

### CODE REVIEW

**Comment by TorutheRedFox** [comment]
isn't it to show current player counts in an infobubble above the level?

**Comment by Slendy** [comment]
Individual story levels are supposed to already include the player counts though, so it would be redundant if it were just for displaying the info.

**Review by jvyden — APPROVED** [review]
LGTM

**Comment by TorutheRedFox** [comment]
actually thinking about it, didn't developer slots show up in hearted lists? maybe it's for that?

**Pull request merged**
