### PR TITLE
User settings, level settings, language and timezone selection and more.

### LINKED ISSUE #197: Add The Ability To Edit Your Profile Description On The Website
We should have the ability of editing your profile description on the website, like LBP.me did.

### LINKED ISSUE #216: Being able to change profile pictures via the website
I had an idea; what if we made it so we could change profile pictures through the website? so you didn't have to import an image on lbp1, since some people don't have lbp1. this is mainly to compensate for that.

### LINKED ISSUE #218: Add ability to transfer account to different e-mail

### LINKED ISSUE #268: Language selection
The title is self-explanatory, Basically a selection of languages if the user does not understand English. This can probably be done by making localization files for each language, and users who wants to volunteer on localizing. For example, Me, I can probably do Danish. and I have a few more friends worldwide that can probably do some other languages. OH YEAH NEVER USE GOOGLE TRANSLATE, ITS INACCURATE.

I recommend using flags as well, It's to make selecting a language easier. I can probably help with flags since I learnt too much on flags.
You can get flags here which I feel best fit. http://www.famfamfam.com/lab/icons/flags/

How it would look like.

### LINKED ISSUE #354: Add ability for users to change the name/description and delete their own levels on the website

### LINKED ISSUE #357: Verification Mail lacking a page
Currently you get a 500 error when Lighthouse sends you a verification mail, and while it works, I've seen many people find it confusing. I think a specific page that tells you that a mail has been sent would help to clear up confusion.
image

### PR DESCRIPTION
**Pull request by Slendy**
It's Slendy back at it again with another pull request and this time we got a juicy one. Nobody actually reads these so I'm just gonna list all the changes

- Users now have a settings button on their profile that when clicked goes to a new settings page.
- Users can now select what language they prefer and it will override their system setting. (Closes #268)
- Users can now select what timezone they prefer to see timestamps in.
- Users can now upload custom images for their profile icon (Closes #216)
- Users can now set their biography from the website (Closes #197)
- Users can now change their email through the settings page (Closes #218)
- The reset password button has been moved from the user page to the user settings page
- Levels now have a settings button that also redirects to a new settings page.
- Levels can have their titles and descriptions edited.
- Levels can have their labels edited from the website.
- Levels can be unpublished from the website. (Closes #354)
- Levels can have custom images uploaded for their icon.
- Levels now display what day they were uploaded on
- Moderators can also access the settings page for any level and any user but they are not permitted to change a user's language, timezone, or email.
- On instances with email verification users will now be required to complete email verification before they log in to the game server or interact with the website
- Fixed an issue where transparent level icons wouldn't display the slot background image underneath
- Fixed an issue where if the email server was unavailable the server would throw an exception, now the page informs the user that sending the email failed and to try again later. (Closes #357)
- Fixed an issue where transparency in TEX files would be lost when converting to PNG (Note: PNG files will have to be regenerated to restore proper transparency)
- Fixed an issue where users could use an already registered email in the case where an instance enabled mail support after users had registered
- Tweaked the translations of some labels that I had missed.

# Pictures
User settings page
User settings page
Level settings page
Level settings page
New level uploaded date and edit icon
New level date and icon

### CODE REVIEW

**Comment by m88youngling** [comment]
WHOAH EPIC

**Comment by Ezoiar** [comment]
W

**Comment by vilijur** [comment]
i'm tired of my profile picture being squished in LBP1.
soon that'll be an issue no more.

**Comment by Ezoiar** [comment]
#297

**Comment by Slendy** [comment]
> #297

Right now you can’t change your username through the settings page even though it’s there as an input. I left it out so that it can be sorted out in the future because we haven’t had a concrete decision on name changes yet.

**Comment by KairosEasyBro** [comment]
LETS GOOOO

**Comment by m88youngling** [comment]
> > #297
> 
> Right now you can’t change your username through the settings page even though it’s there as an input. I left it out so that it can be sorted out in the future because we haven’t had a concrete decision on name changes yet.

In our last discussion about this, I believe we tentatively agreed that it may be a good idea to allow a user to change their username at least once, and then after that threshold is reached they need to seek administrator assistance with username changes. I also could have dreamed about this conversation and it didn't actually happen

**Comment by m88youngling** [comment]
> > #297
> 
> Right now you can’t change your username through the settings page even though it’s there as an input. I left it out so that it can be sorted out in the future because we haven’t had a concrete decision on name changes yet.

In our last discussion about this, I believe we tentatively agreed that it may be a good idea to allow a user to change their username at least once, and then after that threshold is reached they need to seek administrator assistance with username changes

**Comment by Zaprit** [comment]
> > > #297
> > 
> > 
> > Right now you can’t change your username through the settings page even though it’s there as an input. I left it out so that it can be sorted out in the future because we haven’t had a concrete decision on name changes yet.
> 
> In our last discussion about this, I believe we tentatively agreed that it may be a good idea to allow a user to change their username at least once, and then after that threshold is reached they need to seek administrator assistance with username changes. I also could have dreamed about this conversation and it didn't actually happen

as someone who was there I can confirm that this conversation did actually happen

**Comment by m88youngling** [comment]
Since you're the lead developer now, how do you suggest that we go about reviewing your PRs? Maybe the changes could be tested by another developer?

**Comment by Slendy** [comment]
On the lbp1 tags pull request I took awhile to look over it a few times myself and did a sort of self review then I had Zaprit review it. I’ve already noticed a few things that need to be changed but can’t commit them until I get home today.

**Comment by m88youngling** [comment]
Ahh interesting, I gotcha

**Comment by TorutheRedFox** [comment]
> It's Slendy back at it again with another pull request and this time we got a juicy one. Nobody actually reads these so I'm just gonna list all the changes

I do ;P

**Pull request merged**
