### PR TITLE
ratio

### PR DESCRIPTION
**Pull request by sudokoko**

### CODE REVIEW

**Comment by indo2042** [comment]
i support

**Comment by sudokoko** [comment]
watch this take 73 years to get approved

**Review by Slendy — CHANGES_REQUESTED** [review]
L bossman

**Comment by m88youngling** [comment]
goof troop

**Comment by sudokoko** [comment]
> L bossman

deal with it @Slendy

**Comment by Slendy** [comment]
I shouldn't have to say this, but please don't create pull requests or issues unless they contribute something meaningful.

**Pull request closed without merging**
