### PR TITLE
Remove a jvydenism

### PR DESCRIPTION
**Pull request by acidiclight**
Found a try/catch that was being used as a cursed if statement so I fixed it <3

### CODE REVIEW

**Review by sudokoko — APPROVED** [review]
LGTM :trollface:

**Review by Zaprit — APPROVED** [review]
Looks good to me

**Comment by jvyden** [comment]
Just a heads up; I would strongly prefer if my name was not mentioned in future LBP Union commits in this fashion, as I am no longer involved (and do not wish to be) with this project or the group behind it.

I get it if it's some major component I wrote while I was still on the project, but a minor non-issue about a try-catch is not worth being an ass about.

**Comment by sudokoko** [comment]
💀

**Comment by sudokoko** [comment]
> Just a heads up; I would strongly prefer if my name was not mentioned in future LBP Union commits in this fashion, as I am no longer involved (and do not wish to be) with this project or the group behind it.
> 
> I get it if it's some major component I wrote while I was still on the project, but a minor non-issue about a try-catch is not worth being an ass about.

1. There was no need for an unprofessional response like this.

> as I am no longer involved (and do not wish to be) with this project or **the group behind it.**
2. Including "or the group behind it" was not necessary. LBP Union as a whole does not come into play here. Stop trying to use past drama as leverage in a non-existent argument.

> but a minor non-issue about a try-catch is not worth being an ass about.
3. Let's be sure to keep comments professional. Profane language isn't necessary.

Slendy has gone ahead and changed the PR title. We are not going to be able to change the commit message because force-pushes are too risky at the moment.

**Comment by acidiclight** [comment]
> Just a heads up; I would strongly prefer if my name was not mentioned in future LBP Union commits in this fashion, as I am no longer involved (and do not wish to be) with this project or the group behind it.
> 
> I get it if it's some major component I wrote while I was still on the project, but a minor non-issue about a try-catch is not worth being an ass about.

I will be the bigger person and admit that the original PR name and commit message was unnecessary and uncalled-for on my part. This is just my dry sense of humor when working on non-professional/side projects, but it was not warranted. I apologize.

That being said, as previous comments have stated, your response was also unprofessional. You are using past drama with LBPU as leverage to treat a *personal mistake on my part* as a reflection of the entire team. My mistakes aren't LBPU's.

**Comment by jvyden** [comment]
> Including "or the group behind it" was not necessary. LBP Union as a whole does not come into play here. Stop trying to use past drama as leverage in a non-existent argument.

I'm glad we both agree past drama has nothing to do with this, but there is no leverage here; none of us have anything to lose. It's purely a request for my name to not be used in commits under LBP Union going forward. Apologies for making this unclear.

> There was no need for an unprofessional response like this.
> Let's be sure to keep comments professional. Profane language isn't necessary.

I would actually like to apologize for this; my behavior was in response to feeling insulted, and thus a want to express myself more directly. But that doesn't mean it wasn't uncalled for. I promise this will not happen again.

> Slendy has gone ahead and changed the PR title. We are not going to be able to change the commit message because force-pushes are too risky at the moment.

Perfect. This works for me.

**Comment by sudokoko** [comment]
Alright, sounds good. Thank you for clarifying and understanding. Have a good night :)

**Comment by jvyden** [comment]
> I will be the bigger person and admit that the original PR name and commit message was unnecessary and uncalled-for on my part. This is just my dry sense of humor when working on non-professional/side projects, but it was not warranted. I apologize.

I accept your apology.

> That being said, as previous comments have stated, your response was also unprofessional. You are using past drama with LBPU as leverage to treat a _personal mistake on my part_ as a reflection of the entire team. My mistakes aren't LBPU's.

I stated this more clearly in my previous comment, but my intent was not to bring up/involve this incident with past drama or call you out specifically; I only wanted to point out that I do not want to have my name mentioned in this way in future comments under LBP Union. I want to apologize for being disrespectful when trying to convey this.

**Comment by acidiclight** [comment]
Please note that it is unreasonable to expect your name not to be
referenced in commit messages or other discussions related to your code.

This specific instance was unneeded. But you should always expect your name
to be attached to code you contribute, and that it will be referenced
occasionally in discussions. Ideally, in a professional manner, but
nonetheless you need to accept it.

**Comment by Salamni** [comment]
good ending! (Passenger - Let her go)

**Comment by sudokoko** [comment]
I'd like to suggest we lock this thread. If additional conversation is needed, it should be done via Discord or something along those lines.

**Comment by jvyden** [comment]
> Please note that it is unreasonable to expect your name not to be referenced in commit messages or other discussions related to your code. This specific instance was unneeded. But you should always expect your name to be attached to code you contribute, and that it will be referenced occasionally in discussions. Ideally, in a professional manner, but nonetheless you need to accept it.

Correct. It should be noted that when I say I do not want my name mentioned it is purely in cases like this where it is unrelated & unnecessary to the work being done.

I am perfectly okay with it when it is relevant. :+1:

**Comment by jvyden** [comment]
> I'd like to suggest we lock this thread.

Go for it.

**Comment by Salamni** [comment]
byebye thread

**Comment by daggintosh** [comment]
I'm locking the thread, I'd recommend both sides leave each other alone. I'd advise bug fixes or changes be focused on the code itself rather than the person behind it and their skillset. Making fun of a developer or their previous work in a public channel should not be tolerated, no matter how small. We make mistakes and we're learning as we go. Let's be professional and all of us move on.

**Pull request merged**
